# Generated by Django 4.2.6 on 2023-10-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alice_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(max_length=23)),
                ('response', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(max_length=23, primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField(max_length=20)),
                ('reciever_id', models.IntegerField(max_length=20)),
                ('content', models.CharField(max_length=300)),
                ('timestamp', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Room',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_id', models.CharField(max_length=25)),
            ],
        ),
    ]
